/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "secondary": "#535f73",
        "surface-variant": "#d8e2ff",
        "primary": "#003d9b",
        "outline-variant": "#c3c6d6",
        "error-container": "#ffdad6",
        "surface-container-low": "#f1f3ff",
        "surface-container-highest": "#d8e2ff",
        "on-tertiary-fixed-variant": "#812800",
        "surface": "#faf9ff",
        "on-tertiary-container": "#ffc6b2",
        "surface-bright": "#faf9ff",
        "secondary-container": "#d4e0f8",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#380d00",
        "on-primary-container": "#c4d2ff",
        "tertiary": "#7b2600",
        "tertiary-fixed": "#ffdbcf",
        "primary-fixed-dim": "#b2c5ff",
        "primary-fixed": "#dae2ff",
        "tertiary-fixed-dim": "#ffb59b",
        "on-error": "#ffffff",
        "on-primary-fixed": "#001848",
        "background": "#faf9ff",
        "surface-container-high": "#e1e8ff",
        "on-primary-fixed-variant": "#0040a2",
        "inverse-on-surface": "#edf0ff",
        "secondary-fixed": "#d7e3fb",
        "primary-container": "#0052cc",
        "on-secondary-fixed": "#101c2d",
        "inverse-surface": "#1d3054",
        "surface-container": "#e9edff",
        "on-surface": "#051a3e",
        "on-surface-variant": "#434654",
        "outline": "#737685",
        "secondary-fixed-dim": "#bbc7de",
        "surface-dim": "#ccdaff",
        "tertiary-container": "#a33500",
        "on-secondary-container": "#576377",
        "error": "#ba1a1a",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#b2c5ff",
        "on-background": "#051a3e",
        "surface-tint": "#0c56d0",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#3b475b",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        lg: "24px",
        "margin-page": "40px",
        md: "16px",
        base: "4px",
        xl: "32px",
        gutter: "16px",
        sm: "8px",
        xs: "4px",
      },
      fontFamily: {
        "body-md": ["Inter"],
        "code-sm": ["monospace"],
        "headline-lg": ["Inter"],
        "headline-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-xl": ["Inter"],
        "body-sm": ["Inter"],
        "label-md": ["Inter"],
      },
      fontSize: {
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "code-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }],
        "headline-lg": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-xl": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries')
  ],
};
